export const testObjects = [
  {
    _id: "634ac754a956a13abd771083",
    name: "3/4 sit-up",
    instruction:
      "Lie down on the floor and secure your feet. Your legs should be bent at the knees. Place your hands behind or to the side of your head. You will begin with your back on the ground. This will be your starting position. Flex your hips and spine to raise your torso toward your knees. At the top of the contraction your torso should be perpendicular to the ground. Reverse the motion, going only Â¾ of the way down. Repeat for the recommended amount of repetitions.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0001.gif",
    muscle: "abs",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108a",
    name: "45° side bend",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0002.gif",
    muscle: "abs",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108b",
    name: "air bike",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0003.gif",
    muscle: "abs",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108c",
    name: "all fours squad stretch",
    instruction:
      "Start off on your hands and knees, then lift your leg off the floor and hold the foot with your hand. Use your hand to hold the foot or ankle, keeping the knee fully flexed, stretching the quadriceps and hip flexors. Focus on extending your hips, thrusting them towards the floor. Hold for 10-20 seconds and then switch sides.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1512.gif",
    muscle: "quads",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108d",
    name: "alternate heel touchers",
    instruction:
      "Lie on the floor with the knees bent and the feet on the floor around 18-24 inches apart. Your arms should be extended by your side. This will be your starting position. Crunch over your torso forward and up about 3-4 inches to the right side and touch your right heel as you hold the contraction for a second. Exhale while performing this movement. Now go back slowly to the starting position as you inhale. Now crunch over your torso forward and up around 3-4 inches to the left side and touch your left heel as you hold the contraction for a second. Exhale while performing this movement and then go back to the starting position as you inhale. Now that both heels have been touched, that is considered 1 repetition. Continue alternating sides in this manner until all prescribed repetitions are done.  Variations: None",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0006.gif",
    muscle: "abs",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108e",
    name: "alternate lateral pulldown",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0007.gif",
    muscle: "lats",
    equipment: "cable",
  },
  {
    _id: "634ac754a956a13abd77108f",
    name: "ankle circles",
    instruction:
      "Use a sturdy object like a squat rack to hold yourself. Lift the right leg in the air (just around 2 inches from the floor) and perform a circular motion with the big toe. Pretend that you are drawing a big circle with it. Tip: One circle equals 1 repetition. Breathe normally as you perform the movement. When you are done with the right foot, then repeat with the left leg.  Variations: None",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1368.gif",
    muscle: "calves",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108g",
    name: "archer pull up",
    instruction:
      "Grab the pull-up bar with the palms facing forward using a wide grip. As you have both arms extended in front of you holding the bar at a wide grip, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position. Pull your torso up while leaning to the left hand side until the bar almost touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space (no swinging) and only the arms should move. The forearms should do no other work other than hold the bar. After a second of contraction, inhale as you go back to the starting position. Now, pull your torso up while leaning to the right hand side until the bar almost touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar. After a second of contraction, inhale as you go back to the starting position. Repeat steps 3-6 until you have performed the prescribed amount of repetitions for each side.  Caution: If you are new to this exercise and do not have the strength to perform it, using a spotter to hold your legs can help being that it requires putting a lot of stress on the rotator cuffs. Alternatively you can also use a chin assist machine. Variations: If you have developed enough strength to perform this exercise with weights, do so with caution. Side to side chins can be a challenging exercise and if not performed correctly, can cause injury. Before attempting to use weights, make sure you are able to perform the exercise with good form. You can also perform the side to side chins by doing all reps to one side and then the next or by also including the middle movement as well (in which case you would pull up first to the left hand side, then the middle and then the right side). You can use a chin assist machine if you do not have the strength to perform the exercise on your own.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3293.gif",
    muscle: "lats",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108h",
    name: "archer push up",
    instruction:
      "Assume a push-up position with your body straight, supported by your extended arms. Your hands should be outside of shoulder width. This will be your starting position. Initiate the movement by flexing the elbows and leaning to one side, lowering your torso to the ground. Return to the starting position by extending your elbows, pushing yourself back to center. On the next repetition lower yourself to the other side, again returning to the starting position after the rep is complete. Continue alternating until the set is finished.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3294.gif",
    muscle: "pectorals",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108i",
    name: "arm slingers hanging bent knee legs",
    instruction:
      "Take a grip on pull-ups bars; hang with your knees together and your body straight. This will be your starting position. Initiate the movement by flexing the hips and knees, drawing the legs up. Pull the knees up into one side, going above 90 degrees at the hip. Avoid any swinging, performing the exercise with control. Return to the starting position and then perform the movement to the other side. Continue alternating until the set in complete.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2355.gif",
    muscle: "abs",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108j",
    name: "arm slingers hanging straight legs",
    instruction:
      "Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position. Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so. Go back slowly to the starting position as you breathe in. Repeat for the recommended amount of repetitions.  Caution: Perform this exercise slowly and deliberately as it takes some getting used to. Also, do not be hasty and try to use weights on the first time; you'll have enough in your hands by holding your weight and also learning how to balance yourself so that you avoid swinging your torso. As you get more advanced you can hold a dumbbell in between your feet. However, you have to be very careful when adding weight to this exercise as if you add too much too quickly you could get a hernia. Variations: This exercise can also be performed using a vertical bench that makes the exercise easier by supporting your upper back in place and by allowing you to hold yourself by placing your elbows and arms on the side pads.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2333.gif",
    muscle: "abs",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108k",
    name: "arms apart circular toe touch (male)",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3214.gif",
    muscle: "glutes",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108l",
    name: "arms overhead full sit-up (male)",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3204.gif",
    muscle: "abs",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd77108m",
    name: "assisted chest dip (kneeling)",
    instruction:
      "Sit securely in a dip machine, select the weight and firmly grasp the handles. Now keep your elbows in at your sides in order to place emphasis on the triceps. The elbows should be bent at a 90 degree angle. As you contract the triceps, extend your arms downwards as you exhale. Tip: At the bottom of the movement, focus on keeping a little bend in your arms to keep tension on the triceps muscle. Now slowly let your arms come back up to the starting position as you inhale. Repeat for the recommended amount of repetitions.  Variations: You can perform this exercise on parallel bars or on a triceps dip assist machine.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0009.gif",
    muscle: "pectorals",
    equipment: "leverage machine",
  },
  {
    _id: "634ac754a956a13abd77108n",
    name: "assisted hanging knee raise",
    instruction:
      "Hang from a pull-up bar with your arms extended and your feet together (use ab straps if your grip is weak). Lock a slight bend in your knees. This will be your starting position. Without swinging your body, contract your lower abs to raise your knees just past a position in which your thighs are parallel to the floor. As your pelvis begins to curl upward, your partner should place his hand just above your knees to push your legs back down to the starting position, keeping his hand in contact with your legs at all times. Engage your abs and try to resist the movement. With their free hand your partner can push against your lower back to ensure your body doesnâ€™t swing.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0011.gif",
    muscle: "abs",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108o",
    name: "assisted lying calves stretch",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1708.gif",
    muscle: "calves",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108p",
    name: "assisted lying glutes stretch",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1709.gif",
    muscle: "glutes",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108q",
    name: "assisted lying gluteus and piriformis stretch",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1710.gif",
    muscle: "glutes",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108r",
    name: "assisted lying leg raise with lateral throw down",
    instruction:
      "Lie supine on the floor with your feet together; your partner should position one foot on either side of your head and stand upright with his knees slightly bent. Grasp your partner's ankles to stabilize your torso. This will be your starting position. With a slight bend in your knees, do a reverse-crunch movement, raising your feet toward your partner while lifting your hips off the floor. Your partner should grab your ankles and push your feet back toward the start position. Donâ€™t allow your feet to contact the floor and smoothly reverse the direction, repeating for reps.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0012.gif",
    muscle: "abs",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108s",
    name: "assisted lying leg raise with throw down",
    instruction:
      "Lie supine on the floor with your feet together; your partner should position one foot on either side of your head and stand upright with his knees slightly bent. Grasp your partner's ankles to stabilize your torso. This will be your starting position. With a slight bend in your knees, do a reverse-crunch movement, raising your feet toward your partner while lifting your hips off the floor. Your partner should grab your ankles and push your feet back toward the start position. Donâ€™t allow your feet to contact the floor and smoothly reverse the direction, repeating for reps.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0013.gif",
    muscle: "abs",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108t",
    name: "assisted motion russian twist",
    instruction:
      "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees. Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position. Twist your torso to the right side until your arms are parallel with the floor while breathing out. Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side. Repeat for the recommended amount of repetitions.  Variation: As you get more advanced, you can hold a weight with both arms for resistance.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0014.gif",
    muscle: "abs",
    equipment: "medicine ball",
  },
  {
    _id: "634ac754a956a13abd77108u",
    name: "assisted parallel close grip pull-up",
    instruction:
      "Use an assisted pull-up machine or securely attach a heavy-duty band to a pull-up station, securing it around just one knee. The tension should be taut enough to pull that lower leg up. Grasp the bar with an overhand grip just outside shoulder width and hang at full arm extension. This is your start position. Keeping your body straight, contract your lats to pull yourself up as high as you can, driving your elbows down. Slowly release to full arm extension. Repeat for the required number of reps and safely dismount from the apparatus.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0015.gif",
    muscle: "lats",
    equipment: "leverage machine",
  },
  {
    _id: "634ac754a956a13abd77108v",
    name: "assisted prone hamstring",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0016.gif",
    muscle: "hamstrings",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108w",
    name: "assisted prone lying quads stretch",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1713.gif",
    muscle: "quads",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108x",
    name: "assisted prone rectus femoris stretch",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1714.gif",
    muscle: "abs",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd77108y",
    name: "assisted pull-up",
    instruction:
      "Use an assisted pull-up machine or securely attach a heavy-duty band to a pull-up station, securing it around just one knee. The tension should be taut enough to pull that lower leg up. Grasp the bar with an overhand grip just outside shoulder width and hang at full arm extension. This is your start position. Keeping your body straight, contract your lats to pull yourself up as high as you can, driving your elbows down. Slowly release to full arm extension. Repeat for the required number of reps and safely dismount from the apparatus.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0017.gif",
    muscle: "lats",
    equipment: "leverage machine",
  },
  {
    _id: "634ac754a956a13abd77108z",
    name: "assisted seated pectoralis major stretch with stability ball",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1716.gif",
    muscle: "pectorals",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd7710a3",
    name: "assisted side lying adductor stretch",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1712.gif",
    muscle: "adductors",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd7710b3",
    name: "assisted sit-up",
    instruction:
      "Lie face-up on the floor, knees bent and feet flat on the floor about hip-width apart. Cross your fingertips and raise your hands above your head while your partner carefully holds your feet down by stepping on your toes. Your partner should extend one hand out in front of them and above your knees. This will be your starting position. Initiate the movement by contracting your abs to lift your shoulder blades off the floor, reaching to touch your partnerâ€™s hand. Use the strength of your abs to drive higher, not simply reaching with your arms. Donâ€™t allow your shoulder blades to come completely down between reps to keep tension on the muscle. Your partner can move the target point higher or lower, and to one side or the other, to increase the challenge.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1758.gif",
    muscle: "abs",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd7710c3",
    name: "assisted standing chin-up",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1431.gif",
    muscle: "lats",
    equipment: "leverage machine",
  },
  {
    _id: "634ac754a956a13abd7710d3",
    name: "assisted standing pull-up",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1432.gif",
    muscle: "lats",
    equipment: "leverage machine",
  },
  {
    _id: "634ac754a956a13abd7710e3",
    name: "assisted standing triceps extension (with towel)",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0018.gif",
    muscle: "triceps",
    equipment: "assisted",
  },
  {
    _id: "634ac754a956a13abd7710f3",
    name: "assisted triceps dip (kneeling)",
    instruction:
      "Sit securely in a dip machine, select the weight and firmly grasp the handles. Now keep your elbows in at your sides in order to place emphasis on the triceps. The elbows should be bent at a 90 degree angle. As you contract the triceps, extend your arms downwards as you exhale. Tip: At the bottom of the movement, focus on keeping a little bend in your arms to keep tension on the triceps muscle. Now slowly let your arms come back up to the starting position as you inhale. Repeat for the recommended amount of repetitions.  Variations: You can perform this exercise on parallel bars or on a triceps dip assist machine.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0019.gif",
    muscle: "triceps",
    equipment: "leverage machine",
  },
  {
    _id: "634ac754a956a13abd7710g3",
    name: "assisted wide-grip chest dip (kneeling)",
    instruction:
      "Sit securely in a dip machine, select the weight and firmly grasp the handles. Now keep your elbows in at your sides in order to place emphasis on the triceps. The elbows should be bent at a 90 degree angle. As you contract the triceps, extend your arms downwards as you exhale. Tip: At the bottom of the movement, focus on keeping a little bend in your arms to keep tension on the triceps muscle. Now slowly let your arms come back up to the starting position as you inhale. Repeat for the recommended amount of repetitions.  Variations: You can perform this exercise on parallel bars or on a triceps dip assist machine.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2364.gif",
    muscle: "pectorals",
    equipment: "leverage machine",
  },
  {
    _id: "634ac754a956a13abd7710h3",
    name: "astride jumps (male)",
    instruction:
      "Start by standing with your feet together. In one motion, jump your feet out to the side and raise your arms above your head. Immediately reverse the motion by jumping back to the starting position. Repeat for the recommended amount of repetitions.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3220.gif",
    muscle: "cardiovascular system",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd7710i3",
    name: "back and forth step",
    instruction:
      "Start in a relaxed position with one leg slightly forward. This will be your starting position. Skip by executing a step-hop pattern of right-right-step to left-left-step, and so on, alternating back and forth. Perform fast skips by maintaining close contact with the ground and reduce air time, moving as quickly as possible.",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3672.gif",
    muscle: "cardiovascular system",
    equipment: "body weight",
  },
  {
    _id: "634ac754a956a13abd7710j3",
    name: "back extension on exercise ball",
    instruction: " ",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1314.gif",
    muscle: "spine",
    equipment: "stability ball",
  },
];
