name: codecov-coverage-check

on: 
  pull_request:
    branches:
      - main

jobs:
  test-with-coverage-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      - name: install codecov
        run: npm install -g codecov      
      - name: testing with coverage
        run: npm run codecov-coverage